version: '3.8'

services:
  app:
    build: .
    container_name: api_server
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
    ports:
      - "8000:8000"  
    volumes:
      - ./backend:/app/backend  
      - ./frontend:/app/frontend
